#!/bin/bash

BASEURL=https://lb.lb-http.geograndest.caas.camptocamp.com
NUMBER_OF_SAMPLES=100
TYPENAME=geor:public_layer

checkTTFB() {
    local path=$1
    local concurrency=$2
    local maximum_time_ms=$3
    echo "Checking $BASEURL$path"
    local ms=`ab -n $NUMBER_OF_SAMPLES -c $concurrency "$BASEURL$path" | grep Processing | rev | cut -f 1 -d ' ' | rev`
    local s=`echo "scale=3;$ms/1000" | bc`

    if [ $ms -gt $maximum_time_ms ]
    then
        echo -e "\033[01;31m[NOK]\033[00m ($s sec)"
    else
        echo -e "\033[1;36m[OK]\033[00m ($s sec)"
    fi 
}

checkTransferRate() {
    local path=$1
    local concurrency=$2
    local minimum_transfer_rate_kb=$3
    echo "Checking $BASEURL$path"
    local kbs=`ab -n $NUMBER_OF_SAMPLES -c $concurrency "$BASEURL$path" | grep Transfer | rev | cut -d ' ' -f 3 | rev` # [Kbytes/sec] received
    local kbsint=`echo $kbs | cut -f 1 -d '.'`
    if [ $kbsint -lt $minimum_transfer_rate_kb ]
    then
        echo -e "\033[01;31m[NOK]\033[00m ($kbs Kbytes/sec)"
    else
        echo -e "\033[1;36m[OK]\033[00m ($kbs Kbytes/sec)"
    fi 
}


namespace=`echo $TYPENAME | cut -d ':' -f 1`
layername=`echo $TYPENAME | cut -d ':' -f 2`

echo "Testing VECTOR DOWNLOAD service"
echo ""
echo "Maximum 10 seconds to get the first bytes of the service metadata with 10 concurrent requests"
checkTTFB "/geoserver/ows?service=wfs&version=2.0.0&request=GetCapabilities" 10 10000
echo ""
echo "Maximum 30 seconds to get the first bytes of a full dataseries with 10 concurrent requests"
checkTTFB "/geoserver/ows?service=WFS&request=GetFeature&typename=$TYPENAME&outputformat=shape-zip" 10 30000
echo ""

echo "Minimum 512kb/s transfer rate to get a full dataseries with 10 concurrent requests"
checkTransferRate "/geoserver/ows?service=WFS&request=GetFeature&typename=$TYPENAME&OUTPUTFORMAT=shape-zip" 10 512
echo ""

echo "Maximum 30 seconds to get the first bytes of a single feature with 10 concurrent requests"
checkTTFB "/geoserver/ows?service=WFS&version=2.0.0&request=GetFeature&typename=$TYPENAME&count=1" 10 30000

echo "Minimum 512kb/s transfer rate to get a single feature with 10 concurrent requests"
checkTransferRate "/geoserver/ows?service=WFS&version=2.0.0&request=GetFeature&typename=$TYPENAME&count=1" 10 512
echo ""

echo ""
echo "Maximum 10 seconds to get the first bytes of a describe dataseries query with 10 concurrent requests"
checkTTFB "/geoserver/$namespace/$layername/ows?service=WFS&request=GetCapabilities" 10 10000
echo ""
echo "Maximum 10 seconds to get the first bytes of a describe featuretype query with 10 concurrent requests"
checkTTFB "/geoserver/ows?service=WFS&version=2.0.0&request=DescribeFeatureType&typename=$TYPENAME" 10 10000

echo ""
echo ""
echo "Testing VIEW service"
echo ""
echo "Maximum 5 seconds to get the first bytes of a 800x600 8 bit bitmap WMS GetMap with 20 concurrent requests"
checkTTFB "/geoserver/ows?SERVICE=WMS&LAYERS=$TYPENAME&FORMAT=image/tiff8&VERSION=1.3.0&SLD_VERSION=1.1.0&REQUEST=GetMap&CRS=EPSG:3857&BBOX=-20820223,-20820223,20820223,20820223&WIDTH=800&HEIGHT=600" 20 5000
